# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Aaron D. Gonzalez
tagline:             ''
description:         'I''ll <i>occasionally</i> throw some personal projects and professional endeavors up here. ===>'
url:                 http://stubs.github.io
baseurl:             ''
paginate:            5
github: 'https://github.com/stubs'

# About/contact
author:
  name:              Aaron D. Gonzalez
  url:              "aarongonzalez.sucks"
  email:             a.gonzalez979@gmail.com

# Custom vars
version:             1.0.0


#Plugins
gems: [jekyll-paginate]
